name: Java CI with Gradle

on:
  push:
    branches: [new-ci-workflow]
  pull_request:
    branches: [new-ci-workflow]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Build Docker Image
      run: |
        docker build -t wildcat7849/demo-app .
      working-directory: ${{ github.workspace }}

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: |
        docker push wildcat7849/demo-app
      # working-directory: ${{ github.workspace }}
    
    - name: Cleanup
      run: |
        docker rmi wildcat7849/demo-app
      #working-directory: ${{ github.workspace }}
